export const diets = [
  {
    id: 1,
    name: 'Swahili kenyan pilau',
    img: 'img/diet/swahili-kenyan-pilau.jpg',
    category: 'rice',
    des: 'This Swahili Kenyan pilau rice is a must-try! Rice is cooked with beef, potatoes, and spices to give you the most delicious, fluffy, and fragrant dish! This recipe can be made ahead, making it great for meal prep.',
    price: 250,
  },
  {
    id: 2,
    name: 'Kenyan beef pilau',
    img: 'img/diet/Kenyan-Pilau-.jpg',
    category: 'rice',
    des: 'Kenyan pilau rice is a simple dish of rice flavoured with meat stock and spices and sometimes cooked with vegetables. This aromatic rice dish is commonly served at parties and occasions, usually with kachumbari (tomato & cucumber salad).',
    price: 300,
  },
  {
    id: 3,
    name: 'Beef pilau with kachumbari',
    img: 'img/diet/beef-pilau.jpg',
    category: 'rice',
    des: 'Pilau is cooked rice mixed with spices and meat – either beef or chicken and served with a simple homemade salad, locally known as Kachumbari. Kachumbari means salad in Swahili. It is served as a one-pot spicy and aromatic rice dish generally cooked on a traditional coal stove.',
    price: 270,
  },
  {
    id: 4,
    name: 'Beef pilau with kachumbari',
    img: 'img/diet/swahili-chicken-biriani.jpg',
    category: 'rice',
    des: 'Chicken Biryani is a savory chicken and rice dish that includes layers of chicken, rice, and aromatics that are steamed together. The bottom layer of rice absorbs all the chicken juices as it cooks, giving it a tender texture and rich flavor, while the top layer of rice turns out white and fluffy. ',
    price: 320,
  },
  {
    id: 5,
    name: 'Coconut rice',
    img: 'img/diet/coconut-rice.jpg',
    category: 'rice',
    des: 'Fluffy Coconut Rice is the perfect savory side to serve with your favorite grilled meats, in rice bowls piled with beans, grilled veggies, and shredded Kalua Pork, and with many other dishes. Forget plain old white rice and elevate the flavor with coconut milk. Ready in 20 minutes!',
    price: 400,
  },
  {
    id: 6,
    name: 'Kenyan beef stew',
    img: 'img/diet/beef-stew.jpg',
    category: 'beef',
    des: 'I am glad to finally be able to share with you my classic Kenyan beef stew recipe. Beef is slowly stewed in tomatoes, curry powder, and other spices to give you some hearty and fork-tender stew to serve alongside some Swahili pilau or your favorite side dishes!',
    price: 760,
  },
  {
    id: 6,
    name: 'Kenyan beef stew',
    img: 'img/diet/beef-stew.jpg',
    category: 'beef',
    des: 'I am glad to finally be able to share with you my classic Kenyan beef stew recipe. Beef is slowly stewed in tomatoes, curry powder, and other spices to give you some hearty and fork-tender stew to serve alongside some Swahili pilau or your favorite side dishes!',
    price: 760,
  },
];
